//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class angularPost
    {
        public angularPost()
        {
            this.comments = new HashSet<comment>();
        }
    
        public long id { get; set; }
        public string content { get; set; }
        public string postedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string UserIP { get; set; }
        public string UserBrowser { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
    }
}
