//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long id { get; set; }
        public long parentPost { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string UserIP { get; set; }
        public string UserBrowser { get; set; }
        public string commentPostedby { get; set; }
        public int Likes { get; set; }
        public int Hates { get; set; }
    
        public virtual angularPost angularPost { get; set; }
    }
}
